name: NextHire-Deployement-CI-CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json

    - name: Set up environment variables
      run: |
        echo "REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }}" >> .env
        echo "ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }}" >> .env
        echo "COOKIE_SECRET=${{ secrets.COOKIE_SECRET }}" >> .env
        echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
        echo "MongoDB_URI=${{ secrets.MongoDB_URI }}" >> .env
        echo "PORT=${{ secrets.PORT }}" >> .env
        echo "MongoDB_Username=${{ secrets.MongoDB_Username }}" >> .env
        echo "MongoDB_Password=${{ secrets.MongoDB_Password }}" >> .env

    - run: npm ci
    - run: npm run build --if-present

    - name: Start or restart app with PM2
      run: pm2 restart back-end -i max || pm2 start app.js --name back-end -i max
